{
    "name": "Manufaktur", 
    "version": "1.0", 
    "depends": [
        "base",
        "product",
        "sale",
        "account"
    ], 
    "author": "PT.WITACO -Samuel-Haerul",
    "website": "https://www.adhimix.co.id",
    "category": "",
    "summary": "Divisi Manufaktur",
    "description": "Module parent yang ada di divisi Manufaktur",
    "data": [
        "menu.xml",
        "data/ir_sequence.xml",
        "view/pemasaran_view.xml",
        "report/cost_control_report.xml",
        "report/kepuasan_pelanggan_report.xml",
        "report/kontrak_report.xml",
        "report/klaim_report.xml",
        "report/pemeriksaan_alat_report.xml",
        "report/perencanaan_pemasaran_report.xml",
        "report/seleksi_subkontraktor_report.xml",
        "report/seleksi_supplier_report.xml",
        "report/perbaikan_alat_report.xml",
        "report/ketidaksesuaian_produk_report.xml",
        "view/ketidaksesuaian_produk_view.xml",
        "view/seleksi_supplier_view.xml",
        "view/seleksi_subkontraktor_view.xml",
        "view/perencanaan_pemasaran_view.xml",
        "view/kontrak_view.xml",
        "view/maintenance_view.xml",
        "view/cost_control_view.xml",
        "view/evaluasi_penawaran_view.xml",
        "view/instalasi_view.xml",
        "view/kepuasan_pelanggan_view.xml",
        "view/klaim_view.xml",
        "view/pemeriksaan_alat_view.xml",
        "view/inspeksi_pengiriman_view.xml",
        "view/perbaikan_alat_view.xml",
        "wizard/inspeksi_pengiriman_wizard.xml",
        "wizard/info_pasar_wizard.xml",
        "wizard/ketidaksesuaian_produk_wizard.xml",
        "wizard/evaluasi_penawaran_wizard.xml",
        "wizard/klaim_wizard.xml",
        "wizard/kesiapan_pondasi_produk_wizard.xml",
        "wizard/kesiapan_alat_wizard.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application" : True,
}